#ifndef AF2_CONSOLE_COMMANDS_ENVIRONMENT_COMMANDS_HPP
#define AF2_CONSOLE_COMMANDS_ENVIRONMENT_COMMANDS_HPP

#include "../con_command.hpp" // ConCommand, CON_COMMAND, CON_COMMAND_EXTERN

CON_COMMAND_EXTERN(exists);
CON_COMMAND_EXTERN(defined);

CON_COMMAND_EXTERN(type);

CON_COMMAND_EXTERN(var);
CON_COMMAND_EXTERN(const);
CON_COMMAND_EXTERN(enum);
CON_COMMAND_EXTERN(set);
CON_COMMAND_EXTERN(function);
CON_COMMAND_EXTERN(array);
CON_COMMAND_EXTERN(table);

CON_COMMAND_EXTERN(args);
CON_COMMAND_EXTERN(invoke);

CON_COMMAND_EXTERN(sort);

CON_COMMAND_EXTERN(foreach);

CON_COMMAND_EXTERN(find_index);
CON_COMMAND_EXTERN(contains);
CON_COMMAND_EXTERN(size);

CON_COMMAND_EXTERN(push);
CON_COMMAND_EXTERN(pop);
CON_COMMAND_EXTERN(insert);

CON_COMMAND_EXTERN(toggle);

CON_COMMAND_EXTERN(delete);

CON_COMMAND_EXTERN(clear);
CON_COMMAND_EXTERN(assign);
CON_COMMAND_EXTERN(append);

CON_COMMAND_EXTERN(inline);

CON_COMMAND_EXTERN(alias);
CON_COMMAND_EXTERN(unalias);

#endif
