#ifndef AF2_CONSOLE_COMMANDS_GAME_SERVER_STATE_COMMANDS_HPP
#define AF2_CONSOLE_COMMANDS_GAME_SERVER_STATE_COMMANDS_HPP

#include "../con_command.hpp" // ConCommand, CON_COMMAND, CON_COMMAND_EXTERN, GET_COMMAND

CON_COMMAND_EXTERN(start_dedicated);

#endif
