#ifndef AF2_CONSOLE_COMMANDS_GAME_CLIENT_STATE_COMMANDS_HPP
#define AF2_CONSOLE_COMMANDS_GAME_CLIENT_STATE_COMMANDS_HPP

#include "../con_command.hpp" // ConCommand, CON_COMMAND, CON_COMMAND_EXTERN

CON_COMMAND_EXTERN(connect);

#endif
