#ifndef AF2_CONSOLE_COMMANDS_MATH_COMMANDS_HPP
#define AF2_CONSOLE_COMMANDS_MATH_COMMANDS_HPP

#include "../con_command.hpp" // ConCommand, CON_COMMAND, CON_COMMAND_EXTERN
#include "../convar.hpp"      // ConVar...

extern ConVarString cvar_e;
extern ConVarString cvar_pi;

CON_COMMAND_EXTERN(approx_eq);

CON_COMMAND_EXTERN(eq);
CON_COMMAND_EXTERN(ne);
CON_COMMAND_EXTERN(lt);
CON_COMMAND_EXTERN(gt);
CON_COMMAND_EXTERN(le);
CON_COMMAND_EXTERN(ge);

CON_COMMAND_EXTERN(abs);

CON_COMMAND_EXTERN(round);
CON_COMMAND_EXTERN(floor);
CON_COMMAND_EXTERN(ceil);
CON_COMMAND_EXTERN(trunc);
CON_COMMAND_EXTERN(decimal);

CON_COMMAND_EXTERN(neg);

CON_COMMAND_EXTERN(add);
CON_COMMAND_EXTERN(sub);
CON_COMMAND_EXTERN(mul);
CON_COMMAND_EXTERN(div);
CON_COMMAND_EXTERN(mod);
CON_COMMAND_EXTERN(pow);

CON_COMMAND_EXTERN(sqrt);
CON_COMMAND_EXTERN(squared);
CON_COMMAND_EXTERN(hypot);

CON_COMMAND_EXTERN(sin);
CON_COMMAND_EXTERN(cos);
CON_COMMAND_EXTERN(tan);

CON_COMMAND_EXTERN(asin);
CON_COMMAND_EXTERN(acos);
CON_COMMAND_EXTERN(atan);

CON_COMMAND_EXTERN(atan2);

CON_COMMAND_EXTERN(max);
CON_COMMAND_EXTERN(min);
CON_COMMAND_EXTERN(clamp);

CON_COMMAND_EXTERN(log);
CON_COMMAND_EXTERN(ln);
CON_COMMAND_EXTERN(logn);

CON_COMMAND_EXTERN(exp);

CON_COMMAND_EXTERN(sgn);

CON_COMMAND_EXTERN(is_number);
CON_COMMAND_EXTERN(is_integer);

#endif
