#ifndef AF2_CONSOLE_COMMANDS_REMOTE_CONSOLE_CLIENT_COMMANDS_HPP
#define AF2_CONSOLE_COMMANDS_REMOTE_CONSOLE_CLIENT_COMMANDS_HPP

#include "../con_command.hpp" // ConCommand, CON_COMMAND, CON_COMMAND_EXTERN

CON_COMMAND_EXTERN(rcon_login);
CON_COMMAND_EXTERN(rcon_logout);

CON_COMMAND_EXTERN(rcon_abort);

CON_COMMAND_EXTERN(rcon);

CON_COMMAND_EXTERN(rcon_ready);
CON_COMMAND_EXTERN(rcon_status);

#endif
