#ifndef AF2_CONSOLE_COMMANDS_STRING_COMMANDS_HPP
#define AF2_CONSOLE_COMMANDS_STRING_COMMANDS_HPP

#include "../con_command.hpp" // ConCommand, CON_COMMAND, CON_COMMAND_EXTERN

CON_COMMAND_EXTERN(empty);

CON_COMMAND_EXTERN(streq);
CON_COMMAND_EXTERN(istreq);

CON_COMMAND_EXTERN(strcmp);
CON_COMMAND_EXTERN(istrcmp);

CON_COMMAND_EXTERN(strfind);
CON_COMMAND_EXTERN(istrfind);

CON_COMMAND_EXTERN(strcontains);
CON_COMMAND_EXTERN(istrcontains);

CON_COMMAND_EXTERN(strlen);

CON_COMMAND_EXTERN(concat);

CON_COMMAND_EXTERN(substr);

CON_COMMAND_EXTERN(char_at);

CON_COMMAND_EXTERN(escaped);

#endif
