#ifndef AF2_CONSOLE_COMMANDS_UTILITY_COMMANDS_HPP
#define AF2_CONSOLE_COMMANDS_UTILITY_COMMANDS_HPP

#include "../con_command.hpp" // ConCommand, CON_COMMAND, CON_COMMAND_EXTERN, GET_COMMAND

CON_COMMAND_EXTERN(cmdlist);
CON_COMMAND_EXTERN(cvarlist);
CON_COMMAND_EXTERN(find);

CON_COMMAND_EXTERN(help);
CON_COMMAND_EXTERN(wtf);

CON_COMMAND_EXTERN(reset);

CON_COMMAND_EXTERN(default);

CON_COMMAND_EXTERN(cvar_type);

CON_COMMAND_EXTERN(cvar_min);
CON_COMMAND_EXTERN(cvar_max);

CON_COMMAND_EXTERN(get_raw);

#endif
