#ifndef AF2_CONSOLE_COMMANDS_VIRTUAL_MACHINE_COMMANDS_HPP
#define AF2_CONSOLE_COMMANDS_VIRTUAL_MACHINE_COMMANDS_HPP

#include "../con_command.hpp" // ConCommand, CON_COMMAND, CON_COMMAND_EXTERN

CON_COMMAND_EXTERN(current_time);

CON_COMMAND_EXTERN(random_int);
CON_COMMAND_EXTERN(random_float);

CON_COMMAND_EXTERN(wait);
CON_COMMAND_EXTERN(sleep);

CON_COMMAND_EXTERN(done);

CON_COMMAND_EXTERN(run);
CON_COMMAND_EXTERN(await);
CON_COMMAND_EXTERN(await_unlimited);
CON_COMMAND_EXTERN(await_limited);

CON_COMMAND_EXTERN(global);

CON_COMMAND_EXTERN(parent_id);

CON_COMMAND_EXTERN(stop);

CON_COMMAND_EXTERN(ps);

CON_COMMAND_EXTERN(release);

CON_COMMAND_EXTERN(launch);

#endif
