#ifndef AF2_SERVER_SOLID_HPP
#define AF2_SERVER_SOLID_HPP

#include <cstdint> // std::uint32_t

struct Solid final {
	using Flags = std::uint32_t;
	enum Flag : Flags {
		NONE = 0,
		WORLD = 1 << 0,
		RED_ENVIRONMENT = 1 << 1,
		BLUE_ENVIRONMENT = 1 << 2,
		RED_PLAYERS = 1 << 3,
		BLUE_PLAYERS = 1 << 4,
		RED_PROJECTILES = 1 << 5,
		BLUE_PROJECTILES = 1 << 6,
		RED_EXPLOSIONS = 1 << 7,
		BLUE_EXPLOSIONS = 1 << 8,
		RED_SENTRY_GUNS = 1 << 9,
		BLUE_SENTRY_GUNS = 1 << 10,
		MEDKITS = 1 << 11,
		AMMOPACKS = 1 << 12,
		RED_FLAGS = 1 << 13,
		BLUE_FLAGS = 1 << 14,
		RED_PAYLOAD_CARTS = 1 << 15,
		BLUE_PAYLOAD_CARTS = 1 << 16,
		GENERIC_ENTITIES = 1 << 17,

		ENVIRONMENT = RED_ENVIRONMENT | BLUE_ENVIRONMENT,
		PLAYERS = RED_PLAYERS | BLUE_PLAYERS,
		PROJECTILES = RED_PROJECTILES | BLUE_PROJECTILES,
		EXPLOSIONS = RED_EXPLOSIONS | BLUE_EXPLOSIONS,
		SENTRY_GUNS = RED_SENTRY_GUNS | BLUE_SENTRY_GUNS,
		FLAGS = RED_FLAGS | BLUE_FLAGS,
		PAYLOAD_CARTS = RED_PAYLOAD_CARTS | BLUE_PAYLOAD_CARTS,
		RED_ALL = RED_ENVIRONMENT | RED_PLAYERS | RED_PROJECTILES | RED_EXPLOSIONS | RED_SENTRY_GUNS | RED_FLAGS | RED_PAYLOAD_CARTS,
		BLUE_ALL = BLUE_ENVIRONMENT | BLUE_PLAYERS | BLUE_PROJECTILES | BLUE_EXPLOSIONS | BLUE_SENTRY_GUNS | BLUE_FLAGS | BLUE_PAYLOAD_CARTS,
		ALL = static_cast<Flags>(~0)
	};
};

#endif
